version: '2'

services:
    elasticsearch:
        build: ./elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"

    kibana:
        build: ./kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch

    logstash:
        image: logstash:latest
        command: logstash -f /etc/logstash/conf.d/logstash.conf
        volumes:
            - ./logstash/conf:/etc/logstash/conf.d
        ports:
            - "5044:5044"
        links:
            - elasticsearch

    filebeat:
        build: ./filebeat
        volumes:
            - ./filebeat/logs:/tmp/logs
        links:
            - logstash
